### ISSUE TITLE
SVG version of onboarding comics

### ISSUE THREAD

**Issue by karlnaden** [Open-Health-Manager/Design#24]
generate SVG version of the onboarding graphics for use by the development team

**Comment by caroline-berger-mitre** [comment]
Please see svgs here: https://github.com/Open-Health-Manager/Design/tree/main/dev-resources

**Comment by dmpotter44** [comment]
These SVGs don't really help - when we discussed converting the comic to SVGs, it was about redoing the line work such that the comic itself was an SVG. These merely take the existing images and export them into an SVG file - the majority of the files are essentially an SVG with a PNG inside it encoded in Base64. If that's the best we can do, then we might as well take whatever the original resolution images were and use them to create PNGs to use within the phone UI.

**Comment by keolasin** [comment]
I've updated the SVGs, onboarding1-13 in https://github.com/Open-Health-Manager/Design/tree/main/dev-resources, please let me know if these work better.

**Comment by caroline-berger-mitre** [comment]
https://github.com/Open-Health-Manager/Design/tree/main/dev-resources/assets
