### ISSUE TITLE
Identify an open source font to use for onboarding comics

### ISSUE THREAD

**Issue by karlnaden** [Open-Health-Manager/Design#25]
current font is not open source. Find one that is for use instead

**Comment by caroline-berger-mitre** [comment]
we can use the font originally identified: 
<img width="706" alt="image" src="https://user-images.githubusercontent.com/102539996/163584187-5486afc8-2d2f-44a1-a653-c5968e8452f4.png"> https://www.1001fonts.com/back-issues-bb-font.html#license

**Comment by jsonin** [comment]
The Regular and Bold 700 Comic Neue could work:

[https://fonts.google.com/specimen/Comic+Neue?preview.text=You%20can%20share%20your%20[…]health%20information%20about%20you.&preview.text_type=custom](https://fonts.google.com/specimen/Comic+Neue?preview.text=You%20can%20share%20your%20data%20automatically%20during%20an%20emergency.%20First%20responders%20would%20be%20able%20to%20see%20critical%20health%20information%20about%20you.&preview.text_type=custom)
