### ISSUE TITLE
Generate onboarding comic text in styled fashion

### ISSUE THREAD

**Issue by karlnaden** [Open-Health-Manager/Design#26]
styles (bold, italics) not clear from comics, will need styled text to embed in screens

**Comment by caroline-berger-mitre** [comment]
How about using this font face? Looks free https://blambot.com/collections/all-fonts/products/back-issues

**Comment by caroline-berger-mitre** [comment]
If you double click, you should see the font information 
![image](https://user-images.githubusercontent.com/102539996/163581206-cc597630-5122-4f09-bade-95711cf744fa.png)
