### ISSUE TITLE
[design] User sign-up / onboarding wireframe designs

### ISSUE THREAD

**Issue by karlnaden** [Open-Health-Manager/Design#6]
clean up wire frames for user sign-up based on feedback from Harry and others

**Comment by caroline-berger-mitre** [comment]
On the [figma, under 04/06 post feedback](https://www.figma.com/file/EvlNLcUxcRCAezGJNKhQVA/OHM?node-id=0%3A1https://www.figma.com/file/EvlNLcUxcRCAezGJNKhQVA/OHM?node-id=0%3A1). & emailed out to Dan 04/06

**Comment by caroline-berger-mitre** [comment]
On the [figma, under 04/06 post feedback](https://www.figma.com/file/EvlNLcUxcRCAezGJNKhQVA/OHM?node-id=0%3A1https://www.figma.com/file/EvlNLcUxcRCAezGJNKhQVA/OHM?node-id=0%3A1). & emailed out to Dan 04/06
